### ISSUE TITLE
Problem: Indexing 0 titles (at `rebuild_index` command)

### ISSUE THREAD

**Issue by srinathganesh** [divio/aldryn-search#109]
Objective for me:
- Get full text search capability of all CMS Pages
- Whatever is the blog content, will be indexed and searched

Progress:

I created a solr docker
```
version: '2'
services:
  solr:
    image: 'docker.io/bitnami/solr:8-debian-10'
    environment:
      - SOLR_ENABLE_AUTHENTICATION=yes
      - SOLR_ADMIN_USERNAME=foo
      - SOLR_ADMIN_PASSWORD=bar
      - SOLR_CORE=core1
    ports:
      - '8983:8983'
```

Versions:
- django-cms==3.8
- aldryn-search latest
- pysolr latest

Installed apps
```
'cms',
 'haystack',
 'aldryn_common',
 'aldryn_search',
'standard_form',
'spurl',
```

Settings.py extra
```
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://foo:bar@192.168.29.10:8983/solr/core1/',
        'TIMEOUT': 60 * 5,
        'INCLUDE_SPELLING': True,
        'BATCH_SIZE': 100,
    },
    'en': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://foo:bar@192.168.29.10:8983/solr/core1/',
        'TIMEOUT': 60 * 5,
        'INCLUDE_SPELLING': True,
        'BATCH_SIZE': 100,
    },
}

HAYSTACK_ROUTERS = ['aldryn_search.router.LanguageRouter',]
ALDRYN_SEARCH_DEFAULT_LANGUAGE = "en"
ALDRYN_SEARCH_REGISTER_APPHOOK = True
ALDRYN_SEARCH_LANGUAGE_FROM_ALIAS = lambda alias: alias.split('-')[-1]
```

Command:
```
python3 manage.py rebuild_index

output:
Indexing 0 titles
Indexing 0 titles
```
